### PR TITLE
#157 added section title and footer to CauliViewController

### LINKED ISSUE #157: Add a description to the sections of the CauliViewController
As mentioned in #122 it would be handy to add some documentation to the sections in the CauliViewController. The documentation should e.g. describe the affects of disabling a Floret.

### PR DESCRIPTION
**Pull request by pstued**
Fixes #157

### CODE REVIEW

**Comment by pstued** [comment]
screenshot 2019-03-01 at 17 58 51

**Comment by Shukuyen** [comment]
Thanks for the screenshot! The footer explains clearly what happens, when you disable an interceptable floret (should it be "request**s** or response**s**"?). Do you think an additional sentence why displayable florets can't be deactivated would be helpful?

**Comment by pstued** [comment]
> Do you think an additional sentence why displayable florets can't be deactivated would be helpful?

Good question. I was trying to come up with something useful. But I'm not sure if something like "DisplayableForets do not intercept any network traffic." is any good. Also, should we then describe that a DisplayableFloret can also be a InterceptableFloret? I'm more then open for ideas. 

Otherwise I think, if anyone is interested in the difference between Displayables and InterceptableFlorets, they will check the Cauli documentation which will explain it soon. For now describing the effect of the UISwitch seems sufficient for me.

**Comment by Shukuyen** [comment]
I think something along the lines of "Florets only appearing in "Displayable Florets" do not record network traffic themselves and can therefore not be disabled." would suffice. Maybe that's even too longwinded, your comment regarding the documentation is plausible.

**Comment by brototyp** [comment]
> I think something along the lines of "Florets only appearing in "Displayable Florets" do not record network traffic themselves and can therefore not be disabled." would suffice. 

Keep in mind that a Floret can be both. A Displayable **and** an Interceptable Floret.

**Comment by Shukuyen** [comment]
Yes, that's what I tried to tell with "**only** appearing"

**Comment by brototyp** [comment]
> Yes, that's what I tried to tell with "**only** appearing"

Oh yes, you  are completely correct there.

Since @pstued and I are currently rocking a little cauli we thought we want to merge this for now and see if we can improve upon in the context of #156. I hope you are fine with that.

**Review by brototyp — APPROVED** [review]

**Pull request merged**
