### PR TITLE
Add fallback value for configuration parameter to Cauli class #trivial

### PR DESCRIPTION
**Pull request by lukaswuerzburger**
Proposal for #189

### CODE REVIEW

**Review by brototyp — APPROVED** [review]
I love it. Any thoughts, @pstued ?

**Review by pstued — APPROVED** [review]
Thanks for the change :) 👌

**Comment by brototyp** [comment]
Hey @lukaswuerzburger , congratulations to your first merged pull request. Cauli is now your project too. I just invited you as a team member with write permission. We are exited to have you!

**Comment by lukaswuerzburger** [comment]
Yeah! 🎉 😊

**Pull request merged**
